# Generated by Django 2.2.12 on 2020-04-17 05:54

import dashboard.dash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('recurring', models.BooleanField()),
                ('start_date', models.DateField()),
                ('recurring_period', models.SmallIntegerField()),
                ('recurring_unit', models.CharField(choices=[(dashboard.dash.models.PeriodChoice('Daily'), 'Daily'), (dashboard.dash.models.PeriodChoice('Weekly'), 'Weekly'), (dashboard.dash.models.PeriodChoice('Monthly'), 'Monthly'), (dashboard.dash.models.PeriodChoice('Yearly'), 'Yearly')], max_length=10)),
                ('payment_method', models.CharField(choices=[(dashboard.dash.models.PaymentChoice('Cash'), 'Cash'), (dashboard.dash.models.PaymentChoice('Credit Card'), 'Credit Card')], max_length=10)),
                ('labels', models.CharField(max_length=100)),
            ],
        ),
    ]
